version: '3'
services:
  cache:
    image: redis:6.2.6-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  api:
    build: .
    command: npm start
    restart: always
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on:
      - cache
    ports:
      - '3000:3000'
    environment:
      PORT: $PORT
      REDIS_HOST: cache
      REDIS_PORT: $REDIS_PORT
    links:
      - cache
volumes:
  cache:
    driver: local
